### ISSUE TITLE
Update fails on a rich version declaration

### ISSUE THREAD

**Issue by eugene-krivobokov** [littlerobots/version-catalog-update-plugin#17]
**Environment**:

nl.littlerobots.version-catalog-update: 0.2.1
com.github.ben-manes.versions: 0.39.0
Gradle: 7.3.2

libs.versions.toml:

```toml
[versions]
kotlinCoroutines = { strictly = "1.5.2-native-mt" }

[libraries]
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
```

**Scenario**:

```sh
./gradlew versionCatalogUpdate --no-configuration-cache
```

**Unexpected result:**
```
Caused by: java.lang.IllegalStateException: Expected class java.lang.String for key kotlinCoroutines, but was class java.util.LinkedHashMap	
at nl.littlerobots.vcu.VersionCatalogParser.parse(VersionCatalogParser.kt:131)	
at nl.littlerobots.vcu.plugin.VersionCatalogUpdateTask.updateCatalog(VersionCatalogUpdateTask.kt:83)
```

This format is only the one of possible: [toml-dependencies-format](https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format)

**Expected behavior**

It's not obvious how to make a decision in different combinations of a rich version.
There're higher chances that such customizations are because of some workarounds.
Maybe It's safer to start skipping them and warn users about this decision.
