### ISSUE TITLE
Support for updating a single dependency version across multiple Version Catalogs

### ISSUE THREAD

**Issue by ivanalvarado** [littlerobots/version-catalog-update-plugin#55]
Our project shares dependency versions across multiple Version Catalog toml files. For example, we have the following set up:

#### libs.versions.toml
```toml
[versions]
dagger = "2.42"

[libraries]
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
```
#### buildLibs.versions.toml
```toml
[versions]
dagger = "2.42"

[libraries]
hiltAndroidGradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
```

If we need to bump the dagger version, we need to remember to update _all_ toml files that have this dependency version. 

**It would be nice if we could simply pass in the dependency key for the dependency version we wish to update (in this case `dagger`) as an argument to `versionCatalogUpdate` and it update the version across all toml files it's defined in.**
